name: Run Actions Manually

on:
  workflow_dispatch:

jobs:
  process-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          
      - name: Run 'Create AMI' Action
        run: |
          echo "Running 'Create AMI' Action manually..."

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2

      - name: Initialize Packer
        run: |
          packer init ami.pkr.hcl
          
      - name: Run Packer build
        run: |
          packer build ami.pkr.hcl  2>&1 | sudo tee output.txt
          
          # Витягування AMI ID з логів
          AMI_ID=$(tail -2 output.txt | awk 'match($0, /ami-.*/) { print substr($0, RSTART, RLENGTH) }')
          
          # Збереження AMI ID як змінної середовища для подальших кроків
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV

      - name: Use AMI ID
        run: |
          echo "The AMI ID is: ${{ env.AMI_ID }}"

      - name: Set New AMI ID
        uses: punitkashyup/action-secrets-update@v1.0.6
        with:
          repository_owner: vkovalchuk-91
          repository_name: GithubActions3
          secret_name: AMI_ID
          new_secret_value: ${{ env.AMI_ID }}
          github_token: ${{ secrets.GIT_HUB_TOKEN }}
