name: Run Actions Based on Commit Message

on:
  push:
    branches:
      - main

jobs:
  process-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          
      - name: Get commit message
        id: get_message
        run: |
          # Отримуємо останнє повідомлення коміту
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Last commit message: $COMMIT_MESSAGE"
          echo "commit_message=$COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Run 'Create AMI' Action (if message contains 'Create AMI')
        if: contains(env.commit_message, 'Create AMI')
        run: |
          echo "Running 'Create AMI' Action based on commit message..."

      - name: Set up Packer
        if: contains(env.commit_message, 'Create AMI')
        uses: hashicorp/setup-packer@v2

      - name: Initialize Packer
        if: contains(env.commit_message, 'Create AMI')
        run: |
          packer init ami.pkr.hcl
          
      - name: Run Packer build
        if: contains(env.commit_message, 'Create AMI')
        run: |
          packer build ami.pkr.hcl  2>&1 | sudo tee output.txt
          
          # Витягування AMI ID з логів
          AMI_ID=$(tail -2 output.txt | awk 'match($0, /ami-.*/) { print substr($0, RSTART, RLENGTH) }')
          
          # Збереження AMI ID як змінної середовища для подальших кроків
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV

      - name: Use AMI ID
        if: contains(env.commit_message, 'Create AMI')
        run: |
          echo "The AMI ID is: ${{ env.AMI_ID }}"

      - name: Set AMI ID1
        if: contains(env.commit_message, 'Set AMI')
        run: |
          echo "AMI_ID=1111" >> $GITHUB_ENV
             
      - name: Set AMI ID2
        if: contains(env.commit_message, 'Set AMI')
        uses: actions/github-script@v6
        with:
          result-encoding: string
          github-token: ${{ env.GIT_HUB_TOKEN }}
          script: |
            const sodium = require('sodium-native');
            const { data: {key: publicKey, key_id: keyId} } = await github.rest.actions.getRepoPublicKey({...context.repo});
            if (publicKey) {
              const key = Buffer.from(publicKey, 'base64');
              const message = Buffer.from(process.env.AMI_ID);
              const ciphertext = Buffer.alloc(message.length + sodium.crypto_box_SEALBYTES);

              sodium.crypto_box_seal(ciphertext, message, key);
              const encryptedToken = ciphertext.toString('base64');

              await github.rest.actions.createOrUpdateRepoSecret({
                ...context.repo, 
                secret_name: 'AMI_ID',
                encrypted_value: encryptedToken,
                key_id: keyId,
              });
            } else {
              core.error('Failed to fetch the public key. Unable to update secret');
            }
        
      - name: Test AMI ID1
        if: contains(env.commit_message, 'Test AMI')
        env:
          AMI_ID: ${{ secrets.AMI_ID }}
        run: echo "The current AMI_ID is:$AMI_ID"

        

      - name: Run Action 2 (if message contains 'Run AMI')
        if: contains(env.commit_message, 'Run AMI')
        run: |
          echo "Running Action 2 based on commit message..."
          # Додайте тут свої команди для виконання Action 2

      - name: Run Action 3 (if message contains 'Destroy all')
        if: contains(env.commit_message, 'Destroy all')
        run: |
          echo "Running Action 3 based on commit message..."
          # Додайте тут свої команди для виконання Action 3
